node() {
        repoName = gitURL.replaceAll("\\.git", "").split("/")[-1]
        print "Git URL: ${gitURL}, Repository Name:: ${repoName}, microservice: ${microservice}"

        gitCheckout(workspace, gitURL, gitBranch, gitCredentialsId, repoName)

        pom = readMavenPom file: "${repoName}/pom.xml"
        versionNumber = pom.version
        print "POM Artifact Version:: ${versionNumber}"

        repoName = masterJenkinsfileGitURL.replaceAll("\\.git", "").split("/")[-1]
        print "Master Jenkinsfile Git URL: ${masterJenkinsfileGitURL}, Repository Name:: ${repoName}"

        // Checkout the external Jenkinsfile
        gitCheckout(workspace, masterJenkinsfileGitURL, masterJenkinsfileGitBranch, gitCredentialsId, repoName)

        pipeline = load "${repoName}/master-jenkins/${applicationType}/Jenkinsfile"
}

pipeline.main()

/**
 * Clones and checks out the given Git repository branch and commit
 *
 * @param String workspace     Path of the working directory to use
 * @param String url           URL of the Git repository
 * @param String credentialsId Id of the Git credentials to use (From the credentials plugin in Cloudbees)
 */
def gitCheckout(String workspace, String url, String branch, String credentialsId, String repository) {
        withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: "${credentialsId}",
                passwordVariable: 'pass', usernameVariable: 'user']]) {
                sh """
                        rm -rf ${repository}
                        git clone -b ${branch} ${url}
                        cd ${workspace}
                        echo `pwd && ls -l`
                """
        }
}
